version: '3'
services:
  logstash:
    image: logstash:6.4.2
    # volumes:
    #   - ./settings/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    #   - ./settings/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
    #   - ./settings/conf.d:/usr/share/logstash/conf.d:ro
    ports:
      - 9600:9600
      - "5000:5000/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    links:
      - elasticsearch
    networks:
      - esnet

  elasticsearch:
    image: elasticsearch:6.4.2
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: kibana:6.4.2
    ports:
      - 5601:5601
    links:
      - elasticsearch
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
